traducao = {
    "pt": {
        "titulo": "🪙 Análise de Criptomoedas em Tempo Real",
        "descricao": "Monitoramento de preços, tendências e variações das principais criptomoedas ao longo do tempo, com foco em cinco ativos selecionados por sua relevância e representatividade no mercado. Dados obtidos da API do [CoinGecko](https://docs.coingecko.com/).",
        "filtros": "Filtros",
        "periodo": "Período de análise (dias)",
        "moedas": "Selecione a(s) moeda(s):",
        "visualizacao": "Visualização:",
        "log": "Escala logarítmica",
        "linear": "Escala linear",
        "ranking_por": "Ranking por:",
        "preco": "Preço atual",
        "variacao": "Variação (24h)",
        "maxima": "Máxima (período)",
        "minima": "Mínima (período)",
        "atualizado": "Atualizado em",
        "desenvolvido": "Desenvolvido por",
        "alerta": "⚠️ Selecione pelo menos uma criptomoeda para visualizar os dados.",
        "insight_alta": "lidera a alta",
        "insight_queda": "lidera a queda",
        "insight_vol": "é a mais volátil",
        "tag1": "acima da mediana",
        "tag2": "abaixo da mediana",
        "indicadores": "🔹Indicadores de Performance",
        "aba_mercado": "🔹Comportamento de Mercado",
        "aba1": "📈 Tendência e desempenho",
        "aba2": "📊 Ranking e comparação",
        "caption1": "Compara o desempenho relativo das criptomoedas ao longo do tempo, normalizando todas para começar em 100 no início do período, o que permite visualizar claramente quais moedas cresceram ou caíram mais independentemente do preço absoluto.",
        "caption2": "Mostra a dispersão dos preços ao longo do período (normalizados), evidenciando o quanto cada criptomoeda varia em torno de seu valor típico, o que permite identificar quais são mais voláteis ou mais estáveis.",
        "eixo_preco": "Preço (USD)",
        "eixo_preco_atual": "Preço atual (USD)",
        "moeda_legenda": "Criptomoedas",
        "moeda_legenda2": "Criptomoeda",
        "variacao_pct": "Variação (%)",
        "Data": "Data",
        "grafico1": "Evolução do preço das criptomoedas nos últimos {periodo} dias (escala {escala})",
        "grafico2": "Variação percentual das criptomoedas (base 100) nos últimos {periodo} dias",
        "grafico3": "Ranking das criptomoedas por {tipo} na cotação atual",
        "grafico4": "Distribuição normalizada de preços por criptomoeda (volatilidade)"
    },
    "en": {
        "titulo": "🪙 Real-Time Cryptocurrency Analysis",
        "descricao": "Monitoring prices, trends and variations of major cryptocurrencies over time, focusing on five key assets. Data sourced from [CoinGecko](https://docs.coingecko.com/) API.",
        "filtros": "Filters",
        "periodo": "Analysis period (days)",
        "moedas": "Select cryptocurrency(ies):",
        "visualizacao": "Visualization:",
        "log": "Log scale",
        "linear": "Linear scale",
        "ranking_por": "Ranking by:",
        "preco": "Current price",
        "variacao": "Change (24h)",
        "maxima": "Max (period)",
        "minima": "Min (period)",
        "atualizado": "Updated at",
        "desenvolvido": "Developed by",
        "alerta": "⚠️ Select at least one cryptocurrency.",
        "insight_alta": "leads gains",
        "insight_queda": "leads losses",
        "insight_vol": "is the most volatile",
        "tag1": "above median",
        "tag2": "below median",
        "indicadores": "🔹Performance Indicators",
        "aba_mercado": "🔹Market Behavior",
        "aba1": "📈 Trend & performance",
        "aba2": "📊 Ranking & comparison",
        "caption1": "Compares the relative performance of cryptocurrencies over time, normalizing all to start at 100 at the beginning of the period, which allows you to clearly see which coins grew or fell more regardless of absolute price.",
        "caption2": "Shows the dispersion of prices over the period (normalized), highlighting how much each cryptocurrency varies around its typical value, which allows you to identify which are more volatile or more stable.",
        "eixo_preco": "Price (USD)",
        "eixo_preco_atual": "Current price (USD)",
        "moeda_legenda": "Cryptocurrencies",
        "moeda_legenda2": "Cryptocurrency",
        "variacao_pct": "Change (%)",
        "Data": "Date",
        "grafico1": "Price evolution of cryptocurrencies over the last {periodo} days ({escala} scale)",
        "grafico2": "Percentage change of cryptocurrencies (base 100) over the last {periodo} days",
        "grafico3": "Ranking of cryptocurrencies by {tipo} in current price",
        "grafico4": "Normalized price distribution by cryptocurrency (volatility)"
    }
}