name: Ingestao Crypto

on:
  schedule:
    - cron: "0 */6 * * *"  # a cada 6 horas
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar script de ingestão
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python ingestao.py
